### ISSUE TITLE
add opacity utility for f7 items

### ISSUE THREAD

**Issue by DivadNojnarg** [RinteRface/shinyMobile#75]
Sometimes, iOS and android widgets are transparent. This might be a good addition to the package. For instance see:

```css
.class-name {
  opacity:0.5;
}
```

Maybe try to be more clever
